version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tracker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: tracker-backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tracker_db
      - VITE_SEPOLIA_RPC_URL=${VITE_SEPOLIA_RPC_URL}
      - VITE_CONTRACT_ADDRESS=${VITE_CONTRACT_ADDRESS}
      - VITE_IPFS_API_KEY=${VITE_IPFS_API_KEY}
      - VITE_COPROCESSOR_URL=${VITE_COPROCESSOR_URL}
      - VITE_COPROC_HMAC_KEY=${VITE_COPROC_HMAC_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ../private-ledger-flow
      dockerfile: Dockerfile
    container_name: tracker-frontend
    environment:
      - VITE_SEPOLIA_RPC_URL=${VITE_SEPOLIA_RPC_URL}
      - VITE_CONTRACT_ADDRESS=${VITE_CONTRACT_ADDRESS}
      - VITE_BACKEND_URL=http://localhost:3001
      - VITE_IPFS_API_KEY=${VITE_IPFS_API_KEY}
      - VITE_COPROCESSOR_URL=${VITE_COPROCESSOR_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

